travis:
  secure:
    BINSTAR_TOKEN: YPN51P8Yoa1mTht6VYr1xw5I2ERyqmc1kWxnDW37sjO5eN0YjI64k7uVPFn/V1wP24GzmmZLHJ28eCNStKDC7DL5B6FfbgOWSTIIy+vXx81YDqUSJpOKH1TORoCp1DGdsDbRo3NzWYtSm66BOz0AuJcsBibEIs5GpUGZDIc2QE1judClr3FxPQQdq5j97g8zN/uUUXu0OBhu0ABoqAAgNwVntlh/xwBiJls/aSDXiDFkIypX4XOQK/W0zBu2OSojHuHVKw9DDCc6eEh7nVdqN55pdmJue1V7WNUcX7D9QpaasZuWzOS0be5jt5FsoZe7Rf8T+cFOCGzgp8A1YDhRJ/6YJH9zZRxtvxwqkoTHGCDIv6Mt17y8bSPu3rFdlqA4CJLmfQ2otrqKt8ChdFXIxLbJUTILBoMKDNoX13RUmF5Cfz+MxkzZfQFZM1YWe5v3YvrPjJoK1TRaLMHiIf3y/DQTXiFUliflRVYu0G8Q+IFptlBUcz7gNBC81r/7303JBO3WcT70vYUt3wFlG6F1XjQSv6OkMiiAEqwsloG/IQGJnelgZNjhi7QR0yYDtqzkSGKojTWmC9sgd4wiXMque3LJOuxHJv2OqVs428ysGruA+VTcyew874FMn6uNysFbFjCB17x9nhRIGrH2TgQvbVk/Zr9i2xtNY8DzKX+7tQo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
